const FeatureData = [
  {
    group: 'Smart Product Entry',
    icon: 'electric_bolt',
    title: 'Fast Add',
    text: 'Add products in seconds with minimal fields.',
    id: 'prod_1',
  },
  {
    group: 'Smart Product Entry',
    icon: 'edit',
    title: 'Easy Update',
    text: 'Edit product info quickly and keep inventory fresh. Capture every detail for complete listings and effective analysis.',
    id: 'prod_2',
  },
  {
    group: 'Smart Product Entry',
    icon: 'request_quote',
    title: 'Pricing Proposals',
    text: 'Visualize profit margins and receive calculated pricing suggestions instantly.',
    id: 'prod_3',
  },
  {
    group: 'Inventory Intelligence',
    icon: 'inventory_2',
    title: 'Quick Search Inventory',
    text: 'Find products instantly with powerful search and filter options.',
    id: 'inv_11',
  },
  {
    group: 'Inventory Intelligence',
    icon: 'compare_arrows',
    title: 'Real-Time Price Comparison',
    text: 'Get instant price recommendations based on live market data.',
    id: 'inv_2',
  },
  {
    group: 'Inventory Intelligence',
    icon: 'category',
    title: 'Smart Categories',
    text: 'Customize categories to fit your business and keep inventory organized.',
    id: 'inv_3',
  },
  {
    group: 'Insights',
    icon: 'shopping_cart_checkout',
    title: 'Sales Overview',
    text: 'View totals, transactions, item counts, and payment methods with filters by location, channel, and timeframe.',
    id: 'ins_1',
  },
  {
    group: 'Insights',
    icon: 'insights',
    title: 'Sales Details',
    text: 'Gain deeper insights into trends: best-selling brands, categories, sell-through rates, and aggregates.',
    id: 'ins_1',
  },
  {
    group: 'Insights',
    icon: 'trending_up',
    title: 'Trends',
    text: 'Compare performance year-over-year and anticipate future sales trends across channels and locations.',
    id: 'ins_2',
  },
  {
    group: 'Reports',
    icon: 'assignment_returned',
    title: 'Load-Out Report',
    text: 'Simplify inventory loading to your POS with ready-to-use reports.',
    id: 'rep_1',
  },
  {
    group: 'Reports',
    icon: 'bar_chart',
    title: 'Sales Report',
    text: 'Generate configurable sales reports by date range, category, or product type.',
    id: 'rep_2',
  },
];
export default FeatureData;
