# Generated by Django 5.2.8 on 2025-12-01 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('tag_category', models.CharField(choices=[('style_aesthetics', 'Styles & Aesthetics'), ('material', 'Materials'), ('context_placement', 'Context / Placement')], default='STYLE', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('inv_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', related_query_name='category', to='inventory.producttype')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('prod_image', models.ImageField(upload_to='images/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cost_unit', models.CharField(choices=[('Each', 'Each'), ('Pair', 'Pair'), ('Set', 'Set')], default='Each', max_length=15)),
                ('ai_desc', models.TextField(blank=True)),
                ('fast_notes', models.TextField(blank=True)),
                ('user_desc', models.TextField(blank=True)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_unit', models.CharField(choices=[('Each', 'Each'), ('Pair', 'Pair'), ('Set', 'Set')], default='Each', max_length=15)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(choices=[('Like new', 'Like new'), ('Restored', 'Restored'), ('Used: Excellent', 'Used: Excellent'), ('Used: Very Good', 'Used: Very Good'), ('Used: Good', 'Used: Good'), ('Undefined', 'Undefined')], default='Undefined', max_length=20)),
                ('status', models.CharField(choices=[('acquired', 'Acquired'), ('ready_to_list', 'Ready to list'), ('listed', 'Listed'), ('sold', 'Sold'), ('removed', 'Removed')], default='acquired', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='items', to='inventory.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
