# Generated by Django 5.2.8 on 2025-11-25 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Comparative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('comp_name', models.CharField(blank=True, max_length=255)),
                ('comp_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
            ],
            options={
                'ordering': ['inv_item'],
            },
        ),
        migrations.CreateModel(
            name='InvType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='InvItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='media/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('ai_description', models.CharField(blank=True)),
                ('description', models.CharField(blank=True)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(choices=[('Like new', 'Like new'), ('Restored', 'Restored'), ('Used: Excellent', 'Used: Excellent'), ('Used: Very Good', 'Used: Very Good'), ('Used: Good', 'Used: Good')], default='Restored', max_length=20)),
                ('status', models.CharField(choices=[('acquired', 'Acquired'), ('ready_to_list', 'Ready to list'), ('listed', 'Listed'), ('sold', 'Sold'), ('removed', 'Removed')], default='acquired', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default='none', on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
                ('comparative', models.ManyToManyField(related_name='items', to='inventory.comparative')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(related_name='items', to='inventory.tag')),
                ('cost_UOM', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_uom', to='inventory.uom')),
                ('price_UOM', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_uom', to='inventory.uom')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='comparative',
            name='inv_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comp_items', to='inventory.invitem'),
        ),
        migrations.AddField(
            model_name='category',
            name='inv_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', related_query_name='category', to='inventory.invtype'),
        ),
    ]
