# Generated by Django 5.2.8 on 2025-11-25 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='tag_category',
            field=models.CharField(choices=[('furniture_decor_types', 'Furniture & Decor Types'), ('style_aesthetics', 'Styles & Aesthetics'), ('material', 'Materials'), ('context_placement', 'Context / Placement')], default='STYLE', max_length=50),
        ),
    ]
