# Generated by Django 5.2.8 on 2025-12-03 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='inv_type',
            new_name='product_type',
        ),
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('like_new', 'Like new'), ('restored', 'Restored'), ('used_excellent', 'Used: Excellent'), ('used_very Good', 'Used: Very Good'), ('used_good', 'Used: Good'), ('undefined', 'Undefined')], default='undefined', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='cost_unit',
            field=models.CharField(choices=[('each', 'Each'), ('pair', 'Pair'), ('set', 'Set')], default='each', max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_unit',
            field=models.CharField(choices=[('each', 'Each'), ('pair', 'Pair'), ('set', 'Set')], default='each', max_length=15),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_category',
            field=models.CharField(choices=[('style_aesthetics', 'Styles & Aesthetics'), ('material', 'Materials'), ('context_placement', 'Context / Placement')], default='style', max_length=50),
        ),
    ]
