# Generated by Django 5.2.8 on 2025-11-25 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_tag_tag_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_category',
            field=models.CharField(choices=[('style_aesthetics', 'Styles & Aesthetics'), ('material', 'Materials'), ('context_placement', 'Context / Placement')], default='STYLE', max_length=50),
        ),
    ]
