# Generated by Django 5.2.8 on 2025-12-03 20:36

import django.db.models.deletion
import inventory.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=inventory.models.get_default_category, on_delete=django.db.models.deletion.PROTECT, to='inventory.category'),
        ),
    ]
