# Generated by Django 5.2.8 on 2025-11-26 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_tag_tag_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InvType',
            new_name='ProductType',
        ),
        migrations.RemoveField(
            model_name='invitem',
            name='comparative',
        ),
        migrations.RemoveField(
            model_name='invitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='invitem',
            name='cost_UOM',
        ),
        migrations.RemoveField(
            model_name='invitem',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='invitem',
            name='price_UOM',
        ),
        migrations.RemoveField(
            model_name='invitem',
            name='tags',
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='images/')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('ai_description', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('qty', models.IntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('brand', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=30)),
                ('size', models.CharField(blank=True, max_length=50)),
                ('condition', models.CharField(choices=[('Like new', 'Like new'), ('Restored', 'Restored'), ('Used: Excellent', 'Used: Excellent'), ('Used: Very Good', 'Used: Very Good'), ('Used: Good', 'Used: Good')], default='Restored', max_length=20)),
                ('status', models.CharField(choices=[('acquired', 'Acquired'), ('ready_to_list', 'Ready to list'), ('listed', 'Listed'), ('sold', 'Sold'), ('removed', 'Removed')], default='acquired', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.category')),
                ('cost_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cost_items', to='inventory.uom')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to=settings.AUTH_USER_MODEL)),
                ('price_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_uom', to='inventory.uom')),
                ('tags', models.ManyToManyField(related_name='items', to='inventory.tag')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.URLField()),
                ('comp_name', models.CharField(blank=True, max_length=255)),
                ('comp_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7)),
                ('inv_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comps', to='inventory.product')),
            ],
            options={
                'ordering': ['comp_price'],
            },
        ),
        migrations.DeleteModel(
            name='Comparative',
        ),
        migrations.DeleteModel(
            name='InvItem',
        ),
    ]
