# Generated by Django 5.2.8 on 2025-12-08 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_producttype_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['product_type_id', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='qty',
            new_name='purch_qty',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price_unit',
            new_name='qty_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='sold_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'product_type'), name='unique_category_product_type'),
        ),
    ]
