# Generated by Django 5.2.8 on 2025-12-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_category_options_rename_qty_product_purch_qty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost_unit',
        ),
    ]
