# Generated by Django 5.2.8 on 2025-12-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_remove_product_cost_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('like_new', 'Like new'), ('restored', 'Restored'), ('used_excellent', 'Used: Excellent'), ('used_very_good', 'Used: Very Good'), ('used_good', 'Used: Good'), ('undefined', 'Undefined')], default='undefined', max_length=20),
        ),
    ]
