# Generated by Django 5.2.8 on 2025-12-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_product_sold_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='prod_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
